paths:
    inference_dir: "inference_results"
    results_dir: "results"

model:
    model_type: "open_source"
    model_name: "thuml/Thoth-30B-A3B"
    temperature: 0.0
    max_tokens: 10
    max_length: 8192

datasets:
    chattime:
        test_path: "../datasets/ChatTime/test_chattime.json"
        vali_path: "../datasets/ChatTime/validation_chattime.json"
        num_fewshot: 3
